### ISSUE TITLE
What about Wheezy?

### ISSUE THREAD

**Issue by a-x-** [docker-32bit/debian#2]
Hi!

Thank you for this script,
but can you tell me, is it possible got it under Debian 7 Wheezy?

thanks, again,
and excuse my beginner's English

**Comment by a-x-** [comment]
hm, looked around forks and saw https://github.com/tubia/debian
btw, it not working for me too...

**Comment by dashohoxha** [comment]
Is it working, or NOT working? If not working, why?

**Comment by a-x-** [comment]
'docker-32bit/debian' is not working, because it is based on Debian Jessie paths and some another features...

**Comment by dashohoxha** [comment]
I hope that this patch fixes it: 5a2b7eedfab6a17f67522d2527ca326ce271f476 .
You can try it like this: `./build-image.sh wheezy`
