### ISSUE TITLE
Latest tag on Docker Hub

### ISSUE THREAD

**Issue by pchaigno** [docker-32bit/debian#6]
Would it be possible to add a `latest` tag on Docker Hub (alias to `jessie` for now)?
This would make it possible to use the following syntax in Dockerfiles:

``` Dockerfile
FROM 32bit/debian
```

**Comment by ypid** [comment]
@pchaigno Best practice is to use the release you tested with. But adding the latest tag is probably still not a bad idea.

**Comment by dashohoxha** [comment]
I agree, it is a good idea.
I added it already: https://hub.docker.com/r/32bit/debian/tags/

**Comment by pchaigno** [comment]
Thanks!
